# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - octopress-image-tag
  - octopress-codeblock
  - jekyll-textile-converter
  - jekyll-paginate
  - octopress-quote-tag
  - octopress-codefence
  - octopress-solarized
  - octopress-gist
  - octopress-render-code

# Site settings
title: "Fun On Rails"
description: > # this means to ignore newlines until "email:"
  Journal of a Web Developer #ruby #rails #JS 

email: sandip@funonrails.com
#blog logo
logo: "/assets/images/for_logo.png"
# blog cover
cover: ""

name: 'Sandip Ransing'
author: 'Sandip Ransing'
author_image: "/assets/images/author.jpg"

url: http://funonrails.com
baseurl: ""
permalink: /:year/:month/:title

highlighter: pygments # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
paginate_path: "page/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: <!--more-->
titlecase: false       # Converts page and post titles to titlecase

#used to display twitter cards
twitter_handle: '@sandipransing'

# Build settings
#markdown: kramdown
#kramdown: 
#  parse_block_html: false
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart

# Disqus Comments
disqus_short_name: funonrails
disqus_show_comment_count: true

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/sandipransing
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/sandipransing
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
